FCDR_HIRS/fcdr.py, FCDR_HIRS/matchups.py, FCDR_HIRS/processing/combine_matchups.py
Write out harmonisation files in format requested by Sam.  Closes #22, but need to work on #186 to make it work.
=> Adapt harmonisation files

FCDR_HIRS/fcdr.py, FCDR_HIRS/filters.py
Various improvements of outlier detection
=> Improve outlier detection

FCDR_HIRS/analysis/write_harm_meta.py, FCDR_HIRS/matchups.py, FCDR_HIRS/processing/combine_matchups.py
A host of improvements to the harmonisation matchup files.  Hopefully they're OK now, for I need to move on!
=> Further harm match improvements

FCDR_HIRS/analysis/write_harm_meta.py, FCDR_HIRS/fcdr.py, FCDR_HIRS/matchups.py, FCDR_HIRS/measurement_equation.py, FCDR_HIRS/processing/combine_matchups.py
Add numerous new harmonisation fixes, including fixing a major bug that caused any harmonisation matchup files between the same hirs versions to be garbage.
=> Yet more harm fixes

FCDR_HIRS/effects.py, FCDR_HIRS/exceptions.py, FCDR_HIRS/fcdr.py, FCDR_HIRS/measurement_equation.py, FCDR_HIRS/metrology.py, FCDR_HIRS/processing/generate_fcdr.py
Add implementations for calculation of correlation scales according to CM recipes document.
I still intend to push some more commits to this as it's not final yet.
But the answer is 4.04646028!  :dolphin:
Still same :bug: around for sure.
=> Enhance fcdr uncertainty information

FCDR_HIRS/_fcdr_defs.py, FCDR_HIRS/effects.py, FCDR_HIRS/processing/generate_fcdr.py
Improve error correlation information in β FCDR
=> Improve error correlation information

FCDR_HIRS/metrology.py, FCDR_HIRS/processing/generate_fcdr.py
Gracefully handle calculation of correlation scales when all channels are bad.
=> Robust when all channels bad

FCDR_HIRS/metrology.py
Split out allocation and application of CURUC recipes from higher level function, to make it easier to use for other sensor teams.
=> Split curuc implementation

FCDR_HIRS/fcdr.py, FCDR_HIRS/processing/generate_fcdr.py
Add correlation matrices, length scales, and SRFs.
Closes #169.
=> Format updates

setup.py
Something got botched in the last PR...
=> Reinsert script into setup.py, not sure why it went

FCDR_HIRS/analysis/timeseries.py, FCDR_HIRS/fcdr.py
Various fixes and improvements related to time series.  Closes #263.
=> More timeseries options

FCDR_HIRS/processing/combine_matchups.py
Workaround for https://github.com/pydata/xarray/issues/1849
=> workaround unlimited dims problem

FCDR_HIRS/analysis/inspect_hirs_harm_matchups.py
Improve harmonisation plotting
=> Improve harm plotting

FCDR_HIRS/_fcdr_defs.py, FCDR_HIRS/fcdr.py, FCDR_HIRS/processing/generate_fcdr.py
Add common uncertainty, and more consistently use Toms writer.
Closes #215.
Closes #245.
Still open #269 and #270.
=> Add common uncertainty and adapt to writer

FCDR_HIRS/processing/generate_fcdr.py
Bugfix in the name and units of the SRFs.
=> Bugfix, name&unit of SRF

FCDR_HIRS/analysis/inspect_hirs_harm_matchups.py, FCDR_HIRS/matchups.py, FCDR_HIRS/processing/combine_matchups.py, setup.py
Fix a lot of stuff in the harmonisation input file preparation, most notably the filtering, but also lots of other stuff.  See the individual commits for details.
Fixes #108
Fixes #183
=> Even more harm fixes

FCDR_HIRS/analysis/inspect_hirs_harm_matchups.py, FCDR_HIRS/processing/combine_matchups.py
Plot the characteristics of the harmonisation input files, and derive and write out properties on filters that have been derived therefrom.
=> Improve harm input analysis

FCDR_HIRS/processing/generate_fcdr.py
Workaround for https://github.com/FIDUCEO/FCDRTools/issues/15 so that it doesn't crash my jobs
=> Workaround chunksize valueerror

FCDR_HIRS/fcdr.py, FCDR_HIRS/processing/generate_fcdr.py
=> Use RTTOV rather than ARTS SRFs

FCDR_HIRS/fcdr.py, FCDR_HIRS/processing/generate_fcdr.py
=> Use the FCDRTools name function consistently

FCDR_HIRS/analysis/convert_srfs_with_shift.py
Convert SRFs from RTTOV, applying only the native RTTOV shift.  Do not add my own shift here.
=> Convert SRFs from RTTOV, applying only the native RTTOV shift

FCDR_HIRS/processing/generate_fcdr.py
Improve the flexibility of the FCDR generator my making it easier to use get_piece standalone
=> Make get_piece easier to use standalone

FCDR_HIRS/_fcdr_defs.py, FCDR_HIRS/fcdr.py, FCDR_HIRS/processing/generate_fcdr.py
Add more debug radiances.
Closes #272.
=> More debug info options

FCDR_HIRS/fcdr.py, FCDR_HIRS/processing/generate_fcdr.py
The satellite angle calculation was performed assuming a satellite
position above position 28 rather than between 28 and 29.  Also, my
calculation of crossing the meridian did not make sense, this needs to be
per scanline.
This should fix #304 as reported by @cbulgin
=> Fix bug in satellite angle calculation

FCDR_HIRS/fcdr.py, FCDR_HIRS/metrology.py
Various CURUC-related improvements and fixes.
Fixes #324
=> More curuc fixes

FCDR_HIRS/fcdr.py
The non-linearity was not considered when calculating the slope.  This is
a potentially very serious bug.  Hopefully, this commit fixes #336.
=> Include non-linearity in slope calculation

FCDR_HIRS/_fcdr_defs.py, FCDR_HIRS/fcdr.py, FCDR_HIRS/measurement_equation.py, FCDR_HIRS/processing/generate_fcdr.py
Add to the debug FCDR radiances calculated through symbolic measurement equation.
Two new fields.
This will help to debug stuff.
They should be all the same.
If all is well.
Which it may not be.
=> Add to debug FCDR radiances calculated through symbolic measurement equation

FCDR_HIRS/processing/generate_fcdr.py, setup.py
In FCDR generation make sure my attributes are consistent with the ones defined by the FCDRTools.  See also https://github.com/FIDUCEO/FCDRTools/pull/20.  Ideally both should be pulled together when both ready.
=> Respect fcdrtools attributes

FCDR_HIRS/analysis/test_rself.py, FCDR_HIRS/models.py, FCDR_HIRS/processing/generate_fcdr.py
Split of an abstract class for RSelf, leaving the possibility for other implementations
=> Split of an abstract class for RSelf, leaving the possibility for other implementations

FCDR_HIRS/analysis/calibcounts_stats_per_scanpos.py
Finally push some old commits improving the calibration counts plots, I'm not working on those now
=> Improve calibcounts plot

FCDR_HIRS/analysis/timeseries.py, FCDR_HIRS/fcdr.py
Some small fixes related to timeseries plotting
=> More timeseries fixes

FCDR_HIRS/processing/convert_harm_params.py
Allow to use only 2 rather than 3 harmonisation parameters when generating the harmonisation parameters from Ralfs files
=> update hirs param conversion for 2 params

FCDR_HIRS/fcdr.py, FCDR_HIRS/processing/generate_fcdr.py
Improve the strategy for no calibration situation
=> Improve strategy no calibration

FCDR_HIRS/processing/generate_fcdr.py
Set the correct time epoch in debug and easy.  Fixes #370
=> Set correct time epoch in debug and easy

FCDR_HIRS/processing/generate_fcdr.py
Set platform attribute
Depends on https://github.com/FIDUCEO/FCDRTools/pull/20
=> Set platform attribute

FCDR_HIRS/analysis/monitor_fcdr.py, FCDR_HIRS/common.py
Make the FCDR monitor script more flexible and working
=> Improve fcdr monitor

FCDR_HIRS/analysis/inspect_hirs_harm_matchups.py
Improve the analysis scripts on the harmonisation input files.
=> More k input analysis

FCDR_HIRS/analysis/inspect_hirs_matchups.py, FCDR_HIRS/matchups.py
Make Matchupinspections Work Again
=> Repair matchup inspector

FCDR_HIRS/analysis/plot_flags.py, FCDR_HIRS/common.py
=> Repair hirs flag plotting
