FIDUCEO/FCDR_HIRS

FCDR_HIRS/_fcdr_defs.py, FCDR_HIRS/processing/generate_fcdr.py
Debug version had zero radiance due to incorrect scale factor.
This commit fixes #186.
=> Fix encoding for radiances in debug version.

FCDR_HIRS/processing/generate_fcdr.py
Use from_time.second instead of to_time.second for beginning of file
second.  Fixes #217.
=> Fix filename second bug

FCDR_HIRS/fcdr.py
For some reasons, when there are less scanlines than scan positions, the
flag setting here fails, but it otherwise succeeds.  This does not happen
when passing bad.values, so do that instead.
=> Fix rare bug in flag setting

FCDR_HIRS/analysis/logfile_analysis.py, FCDR_HIRS/processing/generate_fcdr.py
It was crashing when a 6-hour period contained exactly one scanline.  That is doubleplusungood.  Changes such that if there are 1 or 2 it also throws an error and moves on.
=> Account for too few but more than 0 scanlines in 6-hour period

FCDR_HIRS/analysis/determine_optimal_uncertainty_format.py, FCDR_HIRS/analysis/map_single_orbit.py, FCDR_HIRS/analysis/monitor_fcdr.py, FCDR_HIRS/analysis/summarise_fcdr.py, FCDR_HIRS/common.py, FCDR_HIRS/fcdr.py
Fix and enhance monitoring script that plots long-term trends in the FCDR:
* Works again for `v0.8pre`;
* Skip flagged data;
* Allows to plot all satellites in a single plot;
* Use lower BT resolution in summary to reduce memory consumption;
* Same colours for same satellite regardless of what subset plotted;
* Option to pass on desired percentiles;
* Don't needlessly repeat legend;
* Restore grid;
* And some other things I'm forgetting right now.
And in the monitoring script that plots components of a single satellite uncertainty for a short time, make the flags plot higher so they are potentially readable.
=> Fix and enhance plotting of long-term trends in FCDR

FCDR_HIRS/analysis/inspect_orbit_curuc.py, FCDR_HIRS/metrology.py, FCDR_HIRS/processing/generate_fcdr.py, setup.py
This adds full correlationg length vectors to the debug FDCR, and adds the option to return them in `apply_curuc` and related functions.
=> Add full correlation length vectors to debug FCDR

FCDR_HIRS/metrology.py
In the situation where I cannot successfully calculate the length scale,
but return placeholder values to not crash the process, the placeholder
values should include the full correlation vector when asked for.
=> Respect 'return_vectors' in robust copout scenario

FCDR_HIRS/_fcdr_defs.py, FCDR_HIRS/effects.py, FCDR_HIRS/fcdr.py, FCDR_HIRS/measurement_equation.py, FCDR_HIRS/metrology.py, FCDR_HIRS/models.py, FCDR_HIRS/processing/generate_fcdr.py
Make it possible to propagate beyond the summation, essentially by expanding the summation.  Some work was needed to make the necessary bits of code aware of `IndexedBase` quantities, most notably a special dictionary that, where appropriate, understands that `T_PRT[1, 2]` can be derived when a sympy expression with `T_PRT[n, m]` is stored (the `ExpressionDict`).  Fixes #129.  Closes #129.
=> Propagate beyond summation

FCDR_HIRS/fcdr.py, FCDR_HIRS/metrology.py
There are now yet more places in which xarray uses numpy.catch_warnings.  That makes me unhappy, for it triggers the bug at https://bugs.python.org/issue29672 which causes warnings to flood.  Do yet more monkey-patching and other dirty stuff to shut it all up.
=> Workaround xarray catch warnings

FCDR_HIRS/processing/combine_matchups.py
In a rebase merge conflict I accidentally (re-)introduced a bug with spurious harmonisation coords.
This PR both fixes the bug and adds a workaround in the merging routine so it can repair the buggy inputs for a correct merged output file.
Fixes #285.
=> Fix spurious harm coords

FCDR_HIRS/analysis/map_single_orbit.py
The exact format in which flags are described in the netcdf data variable
attributes has changed since I first wrote this function.  Adapt the
plotting to reflect this.
=> Adapt flag mapping to format change

FCDR_HIRS/processing/generate_fcdr.py
Prevent entering catch_warnings so I don't get the same error printed over
and over again.  See https://bugs.python.org/issue29672 and
https://github.com/python/cpython/pull/8232
=> Prevent entering catch_warnings

FCDR_HIRS/processing/generate_fcdr.py
I introduced a bug in #307 where debug fcdr filenames had the label EASY.  Now they have DEBUG.
=> Write debug as debug

FCDR_HIRS/analysis/map_single_orbit.py, FCDR_HIRS/math.py
Plot only a subset of an orbit, optionally leaving out the bitmasks.  If a subset, switch to a Plate Carree projection so that I can label the gridlines (see https://github.com/SciTools/cartopy/issues/881 for current limitations).  Add an option to label one or more pixels as desired.
Closes #311
=> Improve orbit plotting

FCDR_HIRS/fcdr.py
Blackbody radiation was not correctly cached in `self._quantities`, therefore a manual application of the measurement equation, OR the application in the uncertainty estimates, led to ε being applied twice, leading to an incorrect L_IWCT and probably all kinds of troubles down the road.
=> Fix B storage

FCDR_HIRS/fcdr.py
When calculating debug radiances, both slope and offset need to be consistently recalculated when either ε or nonlinearity corrections are left out, otherwise both will be wrong.  This will likely fix #337.
=> in debug radiances, consider ε and non-linearity together consistently

FCDR_HIRS/analysis/calibcounts_stats_per_scanpos.py, FCDR_HIRS/analysis/convert_hirs_l1b_to_nc.py, FCDR_HIRS/analysis/fieldmat.py, FCDR_HIRS/analysis/hirs_iasi_srf_estimation.py, FCDR_HIRS/analysis/inspect_hirs_harm_matchups.py, FCDR_HIRS/analysis/inspect_hirs_matchups.py, FCDR_HIRS/analysis/inspect_orbit_curuc.py, FCDR_HIRS/analysis/map.py, FCDR_HIRS/analysis/map_single_orbit.py, FCDR_HIRS/analysis/monitor_fcdr.py, FCDR_HIRS/analysis/plot_flags.py, FCDR_HIRS/analysis/summarise_fcdr.py, FCDR_HIRS/analysis/test_rself.py, FCDR_HIRS/analysis/timeseries.py, FCDR_HIRS/common.py, FCDR_HIRS/processing/combine_matchups.py, FCDR_HIRS/processing/generate_fcdr.py
Rather than adding everything to the root logger, we will only add to the FCDR_HIRS and typhon loggers, such that a `--verbose` flag on the various scripts does not lead to floods from `matplotlib`s own logging.
=> Do not pollute root logger

FCDR_HIRS/analysis/calibcounts_stats_per_scanpos.py, FCDR_HIRS/analysis/convert_hirs_l1b_to_nc.py, FCDR_HIRS/analysis/corrmat_info_content.py, FCDR_HIRS/analysis/fieldmat.py, FCDR_HIRS/analysis/hirs_iasi_srf_estimation.py, FCDR_HIRS/analysis/inspect_hirs_harm_matchups.py, FCDR_HIRS/analysis/inspect_hirs_matchups.py, FCDR_HIRS/analysis/inspect_orbit_curuc.py, FCDR_HIRS/analysis/map.py, FCDR_HIRS/analysis/map_single_orbit.py, FCDR_HIRS/analysis/monitor_fcdr.py, FCDR_HIRS/analysis/plot_flags.py, FCDR_HIRS/analysis/summarise_fcdr.py, FCDR_HIRS/analysis/test_rself.py, FCDR_HIRS/analysis/timeseries.py, FCDR_HIRS/common.py, FCDR_HIRS/fcdr.py, FCDR_HIRS/math.py, setup.py
This PR removes the pyatmlab dependency by moving `print_or_show` and some other functionality and definitions from `pyatmlab`.  The only remaining `pyatmlab` dependency is in the `hirs_iasi_srf_estimation` script which currently probably doesn`t work anyway as it`s old and hasn't been properly integrated into `FCDR_HIRS` yet.
=> Remove pyatmlab dependency

FCDR_HIRS/fcdr.py
Make sure stored LUT always uses SRF actually used, it was using the wrong SRF before.
=> Make sure stored LUT always uses SRF actually used

FCDR_HIRS/metrology.py
Sometimes exactly one ΔL can be used to calculate correlation lengths,
this will cause failure in interpolation... catch this case
=> Catch the problem if too few lines

FCDR_HIRS/metrology.py
Do not use -1 to fill invalid correlations.  Rather use -2.  The exact
value of -1 can happen, although it is very rare.
=> Don't fill invalid correlations with -1

FCDR_HIRS/fcdr.py
Give up if no space views in data to be calibrated, even if space views
are available in the context.  The alternative would be to expand the data
to be calibrated with context data, but I don't currently have enough
bookkeeping to do so.
=> Give up if no space views in data to be calibrated

FCDR_HIRS/fcdr.py
Be robust when unable to calculate channel correlation matrix due to
all data being invalid.  Now results in a matrix of NaNs rather than an
exception.
=> Robust when channel correlations no valid data

FCDR_HIRS/fcdr.py, FCDR_HIRS/models.py, FCDR_HIRS/processing/generate_fcdr.py
Modified call sequence for FCDR filename creation from
outside store_piece_debug and store_piece_easy to make sure that filename
times are consistent with stored time in file
Relevant code around store_piece function
Also added in new code to do self emission with a simple linear model (zero self emission at start of calibration cycle linear interpolation to  self emission estimated at next cycle. Also updated uncertainty based on how good this model seems to be. Actual uncertainty model can estimate uncertainty scanline by scanline but HRIS code is expecting a single number at the moment so take mean value.
Note also typhon has been modified to do more filtering of Level 1 data with associated updates to Allan deviation calculation.
=> Filename bug, extra Level 1 filtering and new self emission model (linear in time)

FCDR_HIRS/processing/generate_fcdr.py
Somehow the debug2easy statement got lost - now included and code generates EASY FCDR
=> Fix bug in EASY FCDR - missing debug2easy statement
